services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mandrael\EventTagsBundle\:
        resource: '../../*'
        exclude:
            - '../../Resources/contao'
            - '../../ContaoManager'
