services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Autoload alle Services aus src/, außer den Contao-spezifischen Ordnern
    Mandrael\EventTagsBundle\:
        resource: '../../*'
        exclude:
            - '../../Resources/contao'
            - '../../ContaoManager'
            - '../../Resources/public'

    # TagsHelper MUSS public sein, da er über DCA options_callback
    # ohne Dependency Injection instanziert wird (Contao-Spezialfall!)
    Mandrael\EventTagsBundle\Helper\TagsHelper:
        public: true
