services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mandrael\EventTagsBundle\:
        resource: '../../*'
        exclude:
            - '../../Resources/contao'
            - '../../Resources/public'
            - '../../ContaoManager'
            - '../../MandraelEventTagsBundle.php'

    Mandrael\EventTagsBundle\Helper\TagsHelper:
        public: true

    # Der Listener f√ºr den Hook
    Mandrael\EventTagsBundle\EventListener\EventFilterListener:
        tags:
            - { name: contao.hook, hook: getAllEvents }
